// Questions for the "Most Likely To" game
export const questions = [
	'Most likely to adopt a (new) pet',
	'Most likely to argue with someone',
	'Most likely to ask you to borrow them money',
	'Most likely to audition to a reality TV show',
	'Most likely to be afraid of a spider',
	'Most likely to be afraid of the dark',
	'Most likely to be afraid of thunder',
	'Most likely to become a millionaire',
	'Most likely to become a model',
	'Most likely to become an SM influencer',
	'Most likely to borrow you money',
	'Most likely to break a bone',
	'Most likely to break a world record',
	'Most likely to break rules',
	'Most likely to burn a cake',
	'Most likely to burp',
	'Most likely to butt dial someone',
	'Most likely to buy real estate',
	'Most likely to catch a fish',
	'Most likely to catch the flu',
	'Most likely to change their career path',
	'Most likely to change their first name',
	'Most likely to change their opinion about something',
	'Most likely to climb Mount Everest',
	'Most likely to colour their hair a new colour',
	'Most likely to complain',
	'Most likely to correct your grammar',
	'Most likely to win a game of bowling',
	'Most likely to cry because of a sad movie',
	'Most likely to cry when drunk',
	'Most likely to do drugs',
	'Most likely to donate money to a charity',
	'Most likely to drunk call someone',
	'Most likely to fall from a horse',
	'Most likely to fart in public',
	'Most likely to find out about a long lost sibling',
	'Most likely to finish a bar of chocolate in one sitting',
	'Most likely to finish a book the fastest',
	'Most likely to finish a marathon',
	'Most likely to finish a pint of ice cream in one sitting',
	'Most likely to fix a leaking sink',
	"Most likely to forget their mom's birthday",
	'Most likely to gain 10 kilos',
	'Most likely to get (more) tattoos ',
	'Most likely to get a speeding ticket',
	'Most likely to get an STD',
	'Most likely to get arrested ',
	'Most likely to get black out drunk',
	'Most likely to get (financially) broke',
	'Most likely to get fired',
	'Most likely to get injured',
	'Most likely to get into a fender bender',
	'Most likely to get into a fight',
	'Most likely to get into a social media argument',
	'Most likely to get into crossfit',
	'Most likely to get kicked out from a bar',
	'Most likely to get kidnapped',
	'Most likely to get lost in the woods',
	'Most likely to get married abroad',
	'Most likely to get married to a foreigner',
	'Most likely to get paid for sex',
	'Most likely to get plastic surgery',
	'Most likely to get stomach issues from food',
	'Most likely to get upset while playing Monopoly',
	'Most likely to go home first from a party',
	'Most likely to go to a casino',
	'Most likely to go vegan',
	'Most likely to gossip',
	'Most likely to have a threesome ',
	'Most likely to have the most children',
	'Most likely to start a band',
	'Most likely to join a cult',
	'Most likely to join a pyramid scheme',
	'Most likely to join the mile high club',
	'Most likely to knit a sweater',
	'Most likely to laugh at the wrong moment',
	'Most likely to learn a new language',
	'Most likely to listen to ABBA',
	'Most likely to lock themselves out of their place',
	'Most likely to lose 10 kilos',
	'Most likely to lose a personal item',
	'Most likely to lose an argument',
	'Most likely to make a dad joke',
	'Most likely to make a racist joke',
	'Most likely to create an app',
	'Most likely to make new friends while drunk',
	'Most likely to marry someone much older than them',
	'Most likely to marry someone much younger than them',
	'Most likely to move abroad',
	'Most likely to name their child something absurd',
	'Most likely to never pay back the money you borrowed them',
	'Most likely to not finish a new project',
	'Most likely to not take a shower for a week',
	'Most likely to pee in the shower',
	"Most likely to pet a stranger's dog",
	'Most likely to play by the rules',
	'Most likely to puke when drunk ',
	'Most likely to show up early to something',
	'Most likely to show up late',
	'Most likely to sing in the shower',
	'Most likely to skydive',
	'Most likely to slam dunk',
	'Most likely to spend a year travelling',
	'Most likely to spend all their money on something stupid',
	'Most likely to spend the whole day behind the computer',
	'Most likely to spend the whole day indoors',
	'Most likely to spend the whole day outdoors',
	'Most likely to star in a soap opera',
	'Most likely to start a business',
	'Most likely to start discussing politics ',
	'Most likely to steal something',
	'Most likely to talk about sports',
	'Most likely to talk about their pets or children',
	'Most likely to talk to animals',
	'Most likely to tell you "I told you so"',
	'Most likely to win a quiz',
	'Most likely to win an argument',
	'Most likely to win Settlers of Catan',
	'Most likely to win the lottery',
	'Most likely to write a book',
	'Most likely to write an article',
	'Most likely to eat something off the ground',
	'Most likely to never get married',
	'Most likely to call in sick (from work)',
	'Most likely to get lost in a city',
	'Most likely to keep a secret',
	'Most likely to spend all of their savings',
	'Most likely to watch a romantic comedy',
	'Most likely to watch a horror movie',
	'Most likley to start vlogging',
	'Most likely to end up as a stand up comedian',
	'Most likely to fall down the stairs',
	'Most likely to be clumsy ',
	'Most likely to forget their own birthday',
	'Most likely to eat bugs',
	'Most likely to go to the gym',
	'Most likely to become a race car driver',
	'Most likely to win a Nobel prize',
	'Most likely to live in a van',
	'Most likely to build a house',
	'Most likely to learn karate',
	'Most likely to dance',
	'Most likely to sing ',
	'Most likely to learn to play an instrument ',
	'Most likely to get arrested ',
	'Most likely to get into crypto',
	'Most likely to join the army',
	'Most likely to get pregnant',
	'Most likely to fall asleep in public',
	'Most likely to brew their own beer',
	'Most likely to paint or draw',
	'Most likely to go to a nude beach',
	'Most likely to go swimming',
	'Most likely to get hungry',
	'Most likely to fly a plane',
	'Most likely to bungee jump',
	'Most likely to binge watch Netflix',
	'Most likely to be in a musical ',
	'Most likely to put pineapple on a pizza',
	'Most likely to become a kindergarten teacher',
	'Most likely to work at a horse farm ',
	'Most likely to grow their own vegetables',
	'Most likely to grow weed',
	'Most likely to lose their wallet ',
	'Most likely to lose their keys',
	'Most likely to eat desert before dinner',
	'Most likely to go on a date',
	'Most likely to meditate',
	'Most likely to ride a bike',
	"Most likely to fail their driver's exam",
	'Most likely to be a perfectionist',
	'Most likely to embarrass a friend in public',
	'Most likely to join an orgy',
	'Most likely to be sarcastic',
	'Most likely to be a nerd',
	'Most likely to get evicted',
	'Most likely to wake up earliest',
	'Most likely to got o sleep latest',
	'Most likely to bake ',
	'Most likely to go to the cinema',
	'Most likely to join a sports team',
	'Most likely to buy a boat',
	'Most likely to not care',
	'Most likely to be a leader of a group ',
	'Most likely to overthink ',
	'Most likely to have a Tarot reading',
	'Most likely to go to church ',
	'Most likely to volunteer',
	'Most likely to adopt a child',
	'Most likely to make coffee',
	'Most likely to do their taxes first ',
	'Most likely to slack off at work ',
	'Most likely to steal office supplies from work',
	'Most likely to start a podcast',
	'Most likely to flash someone ',
	'Most likely to get a new plant',
	'Most likely to kill a plant ',
	'Most likely to get bitten by a mosquito ',
	'Most likely to get recruited to a new job',
	'Most likely to change their job',
	'Most likely to get a stomach ache ',
	'Most likely to go paragliding ',
	'Most likely to go skiing',
	'Most likely to go diving',
	'Most likely to go fishing',
	'Most likely to know a capital of a country ',
	'Most likely to become a DJ',
	'Most likely to get a sunburn',
	'Most likely to renovate their home',
	'Most likely to speed while driving',
	'Most likely to not listen while someone is talking',
	'Most likely to ask a question during a meeting',
	'Most likely to play Dungeons and Dragons',
	'Most likely to play video games',
	'Most likely to not text back ',
	'Most likely to drink spoiled milk ',
	'Most likely to forget to brush their teeth ',
	'Most likely to forget to pay rent',
	'Most likely to get promoted',
	'Most likely to confront someone',
	'Most likely to get a massage',
	'Most likely to go to a concert',
	'Most likely to get upset about the weather',
	'Most likely to play ping pong',
	'Most likely to help out a friend',
	'Most likely to go to a music festival ',
	'Most likely to finish a bottle of liquor in one evening',
	'Most likely to achieve their goal(s)',
	'Most likely to buy a new gadget',
	'Most likely to subscribe to a new service ',
	'Most likely to get hacked ',
	'Most likely to get scammed',
	'Most likely to move to the woods',
	'Most likely to become an environmental activist ',
	'Most likely to buy a Tesla',
	'Most likely to earn over 6 figures',
	'Most likely to make their own deodorant ',
	'Most likely to go shopping',
	'Most likely to receive a package ',
	'Most likely to send a postcard',
	'Most likely to not have insurance',
	'Most likely to save money ',
	'Most likely to fall asleep while watching something',
	'Most likely to snore',
	'Most likely to go to the amusement park ',
	'Most likely to eat chips ',
	'Most likely to use ketchup with their meal ',
	'Most likely to eat spicy food',
	'Most likely to get fined in public transport ',
	'Most likely to buy Christmas presents last minute',
	'Most likely to get a academic degree ',
	'Most likely to build a snowman',
	'Most likey to build a sand castle ',
	'Most likely to use a baby voice',
	'Most likely to vape ',
	'Most likely to go to the doctor',
	'Most likely to get stuck in an elevator',
	'Most likely to go to McDonalds',
	'Most likely to go on a diet',
	'Most likely to throw a party',
	'Most likely to forget to eat',
	'Most likely to not have breakfast',
	'Most likely to learn the lyrics to a song',
	'Most likely to make sushi',
	'Most likely to carve a pumpkin',
	'Most likely to dress up for a costume party',
	'Most likely to host a dinner party',
	'Most likely to get a flat tire ',
	'Most likely to go on a cruise',
	'Most likely to pick their nose',
	'Most likely to get a piercing',
	'Most likely to get botox',
	'Most likely to run a red light',
	'Most likely to cross the street during a red light',
	'Most likely to do yoga',
	'Most likely to go to the dentist ',
	'Most likely to get braces',
	'Most likely to chop wood',
	'Most likely to get stung by a bee or wasp',
	'Most likely to do arts and crafts',
	'Most likely to get tired',
	'Most likely to leave a party without saying bye',
	'Most likely to work at a call center',
	'Most likely to go slacklining',
	'Most likely to go climbing',
	'Most likely to go travelling alone',
	'Most likely to fall asleep on the train or plane',
	'Most likely to get road rage ',
	'Most likely to get insulted',
	'Most likely to get waxed',
	'Most likely to get a manicure',
	'Most likely to read the Bible',
	'Most likely to argue with their parents',
	'Most likely to call their mom',
	'Most likely to set off the fire alarm',
	'Most likely to become a teacher',
	'Most likely to go to work straight from a night out',
	'Most likley to order takeout ',
	'Most likely to sing karaoke',
	'Most likely to play the guitar ',
	'Most likely to send a gif',
	'Most likely to post on social media',
	'Most likely to take a selfie ',
	'Most likely to cry out of frustration',
	'Most likely to never wash their windows',
	'Most likely to find money on the ground',
	'Most likely to have dietary restrictions at a restaurant',
	'Most likely to look up the menu before going to a restaurant',
	'Most likely to plow snow ',
	'Most likely to go ice skating',
	'Most likely to get an allergic reaction ',
	'Most likely to bake bread',
	'Most likely to be good at something new ',
	'Most likely to order an Uber or a taxi ',
	'Most likely to give a compliment',
	'Most likely to receive a compliment ',
	'Most likely to be in a bad mood ',
	'Most likely to get a vitamin deficiency',
	'Most likely to start but not finish a book',
	'Most likely to become a crypto millionare ',
	'Most likely to smash an item out of anger',
	'Most likely to avoid going to the dentist',
	'Most likely to forget to do their taxes',
	'Most likely to repair a broken item',
	'Most likely to eat mozzarella like an apple',
	'Most likely to jump into cold water',
	'Most likely to go to the sauna',
	'Most likely to travel around the world ',
	'Most likely to become a scientist',
	'Most likely to invent a new gadget  ',
	'Most likely to pain their nails',
	'Most likely to leave the biggest tip from the group ',
	'Most likely to learn to play a new instrument ',
	'Most likely to own a pet bird ',
	'Most likely to get an aquarium with fish',
	'Most likely to go surfing ',
	'Most likely to get a speeding ticket ',
	'Most likely to use public transport without a ticket',
	'Most likely to fall when riding an electric scooter',
	'Most likely to start a clothing line',
	'Most likely to become a president ',
	'Most likely to have family tree connect to a royal family ',
	'Most likely to fail an exam',
	'Most likely to get dehydrated'
];
